[terminal]
vt = 1

[default_session]
command = "tuigreet --time --time-format '%I:%M %p' --greeting 'Welcome!' --cmd Hyprland"
user = "greeter"

[initial_session]
command = "Hyprland"
user = "USER_PLACEHOLDER"

